### ISSUE TITLE
Can't login after update

### ISSUE THREAD

**Issue by coollorenzo** [binhex/arch-koel#3]
After updating I can't login even after reinstalling using standard login credentials email: admin@example.com pw: admin
also I get the following errors in my console:
`[Illuminate\Database\QueryException]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t`
`2017-04-03 10:58:58,713 DEBG 'koel' stdout output:
[PDOException]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t`
BTW: i'm using unraid

**Comment by binhex** [comment]
hi, i think i see the issue, im just doing a build now to see if this fixes the issue, i will report back shortly.

**Comment by binhex** [comment]
ok this is now resolved, there were two issues:-

1. koel dev had changed the default config file for koel to another filename, so it wasnt able to copy and modify.

2. laravel has changed their character set to utf8mb4, which caused incompatibility with the version of mysql i have installed.

both issues are now fixed and the latest image (just built) works on a clean install, let me know how you get on.

**Comment by coollorenzo** [comment]
Updating didn't fix it but reinstalling and removing directory. Worked thanks!
